[package]
name = "front_systems"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
serde = "*"
serde_json = "*"
serde_yaml= "*"
actix-files = "0.3.*"
actix-web-middleware-redirect-scheme = "3.0.0"

[profile.release]
opt-level = 'z'
lto = true